// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJj_aJHXS-EJdj7tx3jypW15HQ5sQ2O8w',
    appId: '1:974718791839:web:cd6be87ff202e7b476f2aa',
    messagingSenderId: '974718791839',
    projectId: 'my-easy-tutorial-e7247',
    authDomain: 'my-easy-tutorial-e7247.firebaseapp.com',
    storageBucket: 'my-easy-tutorial-e7247.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC3w7WDFKd-5kEAS_EHjr8Z3tyLe5wU-Y',
    appId: '1:974718791839:android:9361388c4f04f9ad76f2aa',
    messagingSenderId: '974718791839',
    projectId: 'my-easy-tutorial-e7247',
    storageBucket: 'my-easy-tutorial-e7247.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGhvpNIdrAJ0RaVDxx2IMXViowkmxNAXw',
    appId: '1:974718791839:ios:4885bf7ec35d5ffa76f2aa',
    messagingSenderId: '974718791839',
    projectId: 'my-easy-tutorial-e7247',
    storageBucket: 'my-easy-tutorial-e7247.appspot.com',
    iosClientId: '974718791839-uhlh0vupthmplbsv3q4al0r1jre1g2es.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGhvpNIdrAJ0RaVDxx2IMXViowkmxNAXw',
    appId: '1:974718791839:ios:4885bf7ec35d5ffa76f2aa',
    messagingSenderId: '974718791839',
    projectId: 'my-easy-tutorial-e7247',
    storageBucket: 'my-easy-tutorial-e7247.appspot.com',
    iosClientId: '974718791839-uhlh0vupthmplbsv3q4al0r1jre1g2es.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseSample',
  );
}
